name: Python Automated Tests

on:
  push:
    branches:
      - main  # Runs tests on push to the main branch
  pull_request:  # Runs tests on pull requests
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      - name: Checkout code  # Step 1: Check out your code
        uses: actions/checkout@v3

      - name: Set up Python  # Step 2: Set up a Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify the Python version

      - name: Install dependencies  # Step 3: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests  # Step 4: Run pytest
        run: pytest
